# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f7d399708d2620158cd19a6f83dbba62c526bfae482c43790e1bf5f04bc8509c1d69351a176d5a6bbece653d4632a5db38952defb9e3b8a52348a0fcae74ca4

test:
  secret_key_base: 083c6004a8aef1761e60c0327a8d86911df6f7e37288b765ab7a1a23ab7fbf06105aec4fbc46e15537ebae42e647ba2e7c80e96a468cdf0804c3a8f0cfb0aef4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
